name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install git-crypt
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git-crypt

      - name: Decrypt files with git-crypt
        env:
          GIT_CRYPT_KEY_B64: ${{ secrets.GIT_CRYPT_KEY_B64 }}
        run: |
          echo "$GIT_CRYPT_KEY_B64" | base64 -d > git-crypt.key
          git-crypt unlock git-crypt.key

      - name: Install, build, and upload your site output
        uses: withastro/action@v1
        with:
          node-version: 20
          package-manager: pnpm@latest

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: hedior-cv
          directory: ./dist
